ninety-nine-cats/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :cats, except: :destroy
  root "cats#index"
end

ninety-nine-cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

ninety-nine-cats/app/models/cat.rb
class Cat < ApplicationRecord
    CAT_COLORS = ["Orange", "Black", "White", "Grey", "Brown"]
    
    validates :birth_date, :name, presence: true
    validates :color, inclusion: { in: CAT_COLORS }, presence: true
    validates :sex, inclusion: { in: ['M', 'F']}, presence: true
    validate :birth_date_cannot_be_future

    def birth_date_cannot_be_future
        #valid bday formats "January, 1, 2022" or "MM/DD/YYYY"
        if (self.birth_date <=> DateTime.now) == 1
            errors.add(:birth_date, "Birthdate cannot be in the future")
        end
    end

    def age 
        Date.today.year - birth_date.year
    end
end

ninety-nine-cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ninety-nine-cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
	def index
		@cats = Cat.all
		render :index
	end

	def show
		@cat = Cat.find(params[:id])
		render :show
	end
end

ninety-nine-cats/app/helpers/application_helper.rb
module ApplicationHelper
end

ninety-nine-cats/app/views/cats/_cat.html.erb
<tr> 
	<td><%= cat.name %> </td>
	<td><%= cat.color %> </td>
	<td><%= cat.sex %> </td>
	<td><%= cat.birth_date %> </td>
	<td><%= cat.description %> </td>
	<% if type == :show %>
		<td><a href="<%= cats_url %>">All cats</a></td>
	<% else %>
		<td><a href="<%= cat_url(cat) %>">Cat</a></td>
	<% end %>
</tr>

ninety-nine-cats/app/views/cats/index.html.erb
<table>
    <thead>
        <tr>
            <th> All cats </th>
        </tr>
    </thead>

		<tbody> 
			<% @cats.each do |cat| %>
				<%= render "cat", cat: cat, type: :index %>
			<% end %>
		</tbody>

</table>

ninety-nine-cats/app/views/cats/show.html.erb
<%= render "cat", cat: @cat, type: :show %>

ninety-nine-cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>